# Copyright 2019 Autodesk, Inc.  All rights reserved.
#
# Use of this software is subject to the terms of the Autodesk license agreement
# provided at the time of installation or download, or which otherwise accompanies
# this software in either electronic or hard copy form.
#
#
# jekyll configuration file for ShotGrid Developer Site Environment
#
# For more information, see https://developer.shotgridsoftware.com/tk-doc-generator/


# Site settings
title: SG Developer
description: Resources for ShotGrid Developers.

# i18n configuration for all languages shotgun supports
languages: ["en", "ko", "ja", "zh_CN"]
lang_vars: ["English", "한국어", "日本語", "简体中文"]
default_lang: "en"

# analytics - see https://github.com/hendrikschneider/jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-2114792-9        # Required - replace with your tracking id

# custom google search integration
google_custom_search_id: "015683694229584726942:8l32_vorpny"

# html head metadata: social open graph and favicon
additional_head_html: |
  <meta property="og:image:height" content="1257">
  <meta property="og:image:width" content="2400">
  <meta property="og:title" content="ShotGrid Developer">
  <meta property="og:description" content="This site contains detailed technical reference for all of the ways you can interact with ShotGrid programmatically, as well as tutorials, guides, and other educational resources for learning how to make the best use of all of ShotGrid's integration points.">
  <meta property="og:url" content="https://developer.shotgridsoftware.com">
  <meta property="og:image" content="https://developer.shotgridsoftware.com/site-metadata/og-image.jpg">
  <link rel="apple-touch-icon" sizes="180x180" href="/site-metadata/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/site-metadata/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/site-metadata/favicon-16x16.png">
  <link rel="manifest" href="/site-metadata/site.webmanifest">
  <link rel="mask-icon" href="/site-metadata/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

custom_pre_content: |
  <span id="article-type" style="display:none;" data-swiftype-name="type" data-swiftype-type="enum">Article</span>
  <span id="article-locale" style="display:none;" data-swiftype-name="locale" data-swiftype-type="enum">en-us</span>
  <div class="article-body markdown" data-swiftype-name="body" data-swiftype-type="text">

custom_post_content: </div>


# the url to connect to via the 'edit in github' button
github_editme_path: shotgunsoftware/developer.shotgridsoftware.com/blob/master/docs
