# Copyright 2019 Autodesk, Inc.  All rights reserved.
#
# Use of this software is subject to the terms of the Autodesk license agreement
# provided at the time of installation or download, or which otherwise accompanies
# this software in either electronic or hard copy form.
#

# jekyll configuration file for Shotgun Developer Site Environment

# Site settings
title: SG Developer
description: Resources for Shotgun Developers.

# i18n configuration for all languages shotgun supports
languages: ["en", "ko", "ja", "zh_CN"]
lang_vars: ["English", "한국어", "日本語", "简体中文"]
default_lang: "en"

# analytics - see https://github.com/hendrikschneider/jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-2114792-9        # Required - replace with your tracking id

# html social open graph, metadata and favicon
additional_head_html: |
  <meta property="og:image:height" content="1257">
  <meta property="og:image:width" content="2400">
  <meta property="og:title" content="Shotgun Developer">
  <meta property="og:description" content="This site contains detailed technical reference for all of the ways you can interact with Shotgun programmatically, as well as tutorials, guides, and other educational resources for learning how to make the best use of all of Shotgun's integration points.">
  <meta property="og:url" content="https://developer.shotgunsoftware.com">
  <meta property="og:image" content="https://developer.shotgunsoftware.com/og-image.jpg">
  <link rel="apple-touch-icon" sizes="180x180" href="/developer-beta/site-metadata/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/developer-beta/site-metadata/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/developer-beta/site-metadata/favicon-16x16.png">
  <link rel="manifest" href="/developer-beta/site-metadata/site.webmanifest">
  <link rel="mask-icon" href="/developer-beta/site-metadata/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
